### ISSUE TITLE
Bug with frequency

### ISSUE THREAD

**Issue by T8RIN** [galaxygoldfish/waveslider#4]
I've tested some frequency values, and every value except predefined 0.07 caused laggy animation, it starts running and then breaks and starts again, In other words infinity running effect became broken :(

**Comment by galaxygoldfish** [comment]
That's true, I think it's due to the fact that the wave phase shift float is hard-coded. When I created the library I just tested different values for it until it looked smooth however that only would apply to a single amplitude. 

Since the wave animation is essentially just a sin wave that is constantly phase shifted in a direction, having a different amplitude definitely would affect it being smooth because of how wide the waves are, so I suspect that for the ```phaseShiftFloat``` target value it should be some sort of ratio involving the amplitude so it can always be seamless

[WaveSlider.kt](https://github.com/galaxygoldfish/waveslider/blob/main/waveslider/src/main/java/com/galaxygoldfish/waveslider/WaveSlider.kt)
```kotlin
val infiniteTransition = rememberInfiniteTransition(label = "Wave infinite transition")
    val phaseShiftFloat = infiniteTransition.animateFloat(
        label = "Wave phase shift",
        initialValue = 0F,
        targetValue = 90f, // This value only seems to work for 0.07 amplitude
        animationSpec = infiniteRepeatable(
            animation = keyframes {
                durationMillis = 1000
            },
            repeatMode = RepeatMode.Restart
        )
    ).value
```

**Comment by T8RIN** [comment]
Oh, thanks, will check it now :)
